# -*- coding: utf-8 -*-
"""job_matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuSQab3rcWgOvnG8hb0vKfPoA--GdTEo
"""

import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

nltk.download('punkt')

def compute_similarity(resume_text, job_desc):
    corpus = [resume_text, job_desc]
    vectorizer = TfidfVectorizer(stop_words='english')
    vectors = vectorizer.fit_transform(corpus)
    similarity = cosine_similarity(vectors[0:1], vectors[1:2])[0][0]
    return round(similarity * 100, 2)

def extract_keywords(text, top_n=10):
    words = nltk.word_tokenize(text)
    words = [w.lower() for w in words if w.isalpha()]
    freq_dist = nltk.FreqDist(words)
    return [word for word, freq in freq_dist.most_common(top_n)]